<?php

function customcontact_form_alter(&$form, $form_state, $form_id) {
    if($form_id == 'contact_site_form') {
        // array_push($form['subject'], ['#default_value']);
        $form['subject']['#default_value'] = 'Feedback';
        // $form $subject[$row["#default_value"]] = $row["Feedback"];
        $form['copy']['#default_value'] = 1;
        // ///Shows the array of the form for drill down to desired component///
        // print '<pre>';
        // print_r($form);
        // print '</pre>';
    }
    // if($form_id == 'node_type_form') {
    //     $form['display']['node_submitted']['#default_value'] = 0;
    //     // print '<pre>';
    //     // print_r($form);
    //     // print '</pre>';
    // }

}
